### ISSUE TITLE
How to use environment variables for secrets in the YAML

### ISSUE THREAD

**Issue by vitorbaptista** [transferwise/pipelinewise#203]
Is it possible to use env variables in the YAML files for the secrets, instead of using Ansible Vault? If not, is it a feature you'd consider adding?

**Comment by koszti** [comment]
not possible at the moment, but if it looks beneficial for us, we can consider it. Alternatively feel free to send PRs if you feel like developing. We can review PRs quickly.

**Comment by sokser** [comment]
I have a PR that will allow them to be used in the singer spec that you use: https://github.com/transferwise/pipelinewise/pull/223

**Comment by johnoscott** [comment]
As an example of how this might work, the DBT project supports environment variables in YAML configs like this : 

```yaml
profile:
  target: prod
  outputs:
    prod:
      type: postgres
      host: 127.0.0.1
      # IMPORTANT: Make sure to quote the entire Jinja string here
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      ....
```

https://docs.getdbt.com/docs/env_var
