### ISSUE TITLE
Violates not-null constraint

### ISSUE THREAD

**Issue by lephuhai** [transferwise/pipelinewise#648]
Your command: `pipelinewise run_tap --tap mysql_web_warehouse --target postgres_dwh`

Why **tap-mysql** create a new column to **target-postgres** and foreign key always Null value?

**Your question**
![image](https://user-images.githubusercontent.com/7351351/110749928-52afc400-8274-11eb-960f-607e57904af7.png)

And after the data source is updated, I re-run the pipeline again, and then it throws an error: **violates not-null constraint**.
Please help me fix this issue.

Details exception:
```
time=2021-03-11 07:16:18 logger_name=pipelinewise log_level=INFO message=Profiling mode not enabled
time=2021-03-11 07:16:18 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=Running mysql_web_warehouse tap in postgres_dwh target
time=2021-03-11 07:16:18 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=No table available that needs to be sync by fastsync
time=2021-03-11 07:16:18 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=Table(s) selected to sync by singer: ['pushsale-advertisers', 'pushsale-leads', 'pushsale-leads_meta', 'pushsale-offers', 'pushsale-opportunities', 'pushsale-opportunity_attributes', 'pushsale-orders', 'pushsale-users']
time=2021-03-11 07:16:18 logger_name=pipelinewise.cli.commands log_level=INFO message=Writing output into /root/.pipelinewise/postgres_dwh/mysql_web_warehouse/log/postgres_dwh-mysql_web_warehouse-20210311_071618.singer.log
time=2021-03-11 07:16:19 logger_name=pipelinewise.cli.pipelinewise log_level=ERROR message=Command failed. Return code: 1
Error(s) found:
psycopg2.errors.NotNullViolation: null value in column "id_20210311_0438" violates not-null constraint

Full log: /root/.pipelinewise/postgres_dwh/mysql_web_warehouse/log/postgres_dwh-mysql_web_warehouse-20210311_071618.singer.log.failed
Traceback (most recent call last):
  File "/app/pipelinewise/pipelinewise/cli/pipelinewise.py", line 1035, in run_tap
    stream_buffer_size=stream_buffer_size)
  File "/app/pipelinewise/pipelinewise/cli/pipelinewise.py", line 869, in run_tap_singer
    commands.run_command(command, self.tap_run_log_file, update_state_file)
  File "/app/pipelinewise/pipelinewise/cli/commands.py", line 365, in run_command
    raise RunCommandException(f'Command failed. Return code: {proc_rc}\n'
pipelinewise.cli.commands.RunCommandException: Command failed. Return code: 1
Error(s) found:
psycopg2.errors.NotNullViolation: null value in column "id_20210311_0438" violates not-null constraint

Full log: /root/.pipelinewise/postgres_dwh/mysql_web_warehouse/log/postgres_dwh-mysql_web_warehouse-20210311_071618.singer.log.failed
time=2021-03-11 07:16:19 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=
-------------------------------------------------------
TAP RUN SUMMARY
-------------------------------------------------------
    Status  : FAILED
    Runtime : 0:00:00.941220
-------------------------------------------------------
```

**Comment by Samira-El** [comment]
Hey,

I'm not sure I'm understanding your questions, but I'll try.

re the columns `id_20210311_0438` and `group_id_20210311_0438`, this is column versioning which happens when the columns in the source (in your case, mysql table) changes their type. Read more here: https://transferwise.github.io/pipelinewise/user_guide/schema_changes.html

re `psycopg2.errors.NotNullViolation: null value in column "id_20210311_0438" violates not-null constraint`
It simply means that target-postgres has received a new record to insert where the value in `id_20210311_0438` column that already exists.
Try to resync with FastSync `pipelinewise --tap mysql_web_warehouse --target postgres_dwh sync_table --tables pushsale-users `

**Comment by lephuhai** [comment]
Dear @Samira-El ,

Follow your instruction, I keep going to run command to sync_tables like this:

```bash
$ pipelinewise sync_tables --target postgres_dwh --tap mysql_web_warehouse --tables pushsale.users
```
And everything from our data is correct.
![image](https://user-images.githubusercontent.com/7351351/110762509-729ab400-8283-11eb-83f4-201fa84f2f92.png)

Keep thing about that, I updated the data source in the mysql database and run the pipeline again and got an exception, and the data become the incorrect schema.

```bash
$ pipelinewise run_tap --tap mysql_web_warehouse --target postgres_dwh
```
![image](https://user-images.githubusercontent.com/7351351/110762332-3ff0bb80-8283-11eb-9f02-ceb8b4d06379.png)

```
(pipelinewise) root@pipelinewise-588d944fb8-qt5z2:~/.pipelinewise/postgres_dwh/mysql_web_warehouse# pipelinewise run_tap --tap mysql_web_warehouse --target postgres_dwh
time=2021-03-11 08:56:09 logger_name=pipelinewise log_level=INFO message=Profiling mode not enabled
time=2021-03-11 08:56:09 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=Running mysql_web_warehouse tap in postgres_dwh target
time=2021-03-11 08:56:09 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=No table available that needs to be sync by fastsync
time=2021-03-11 08:56:09 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=Table(s) selected to sync by singer: ['pushsale-advertisers', 'pushsale-leads', 'pushsale-leads_meta', 'pushsale-offers', 'pushsale-opportunities', 'pushsale-opportunity_attributes', 'pushsale-orders', 'pushsale-users']
time=2021-03-11 08:56:09 logger_name=pipelinewise.cli.commands log_level=INFO message=Writing output into /root/.pipelinewise/postgres_dwh/mysql_web_warehouse/log/postgres_dwh-mysql_web_warehouse-20210311_085609.singer.log
time=2021-03-11 08:56:11 logger_name=pipelinewise.cli.pipelinewise log_level=ERROR message=Command failed. Return code: 1
Error(s) found:
psycopg2.errors.NotNullViolation: null value in column "id_20210311_0856" violates not-null constraint

Full log: /root/.pipelinewise/postgres_dwh/mysql_web_warehouse/log/postgres_dwh-mysql_web_warehouse-20210311_085609.singer.log.failed
Traceback (most recent call last):
  File "/app/pipelinewise/pipelinewise/cli/pipelinewise.py", line 1035, in run_tap
    stream_buffer_size=stream_buffer_size)
  File "/app/pipelinewise/pipelinewise/cli/pipelinewise.py", line 869, in run_tap_singer
    commands.run_command(command, self.tap_run_log_file, update_state_file)
  File "/app/pipelinewise/pipelinewise/cli/commands.py", line 365, in run_command
    raise RunCommandException(f'Command failed. Return code: {proc_rc}\n'
pipelinewise.cli.commands.RunCommandException: Command failed. Return code: 1
Error(s) found:
psycopg2.errors.NotNullViolation: null value in column "id_20210311_0856" violates not-null constraint

Full log: /root/.pipelinewise/postgres_dwh/mysql_web_warehouse/log/postgres_dwh-mysql_web_warehouse-20210311_085609.singer.log.failed
time=2021-03-11 08:56:11 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=
-------------------------------------------------------
TAP RUN SUMMARY
-------------------------------------------------------
    Status  : FAILED
    Runtime : 0:00:01.200733
-------------------------------------------------------
```

I always keep to trying run `run_tap` command into crontab, but destination data is going wrong and exception process.
Follow into documentation from here: https://transferwise.github.io/pipelinewise/user_guide/scheduling.html#

**Comment by lephuhai** [comment]
FastSync command: `pipelinewise sync_tables --target postgres_dwh --tap mysql_web_warehouse`
FastSync have an warning: **Incorrect datetime value**

```
/app/pipelinewise/pipelinewise/fastsync/mysql_to_postgres.py:99: Warning: (1411, "Incorrect datetime value: '0000-00-00 00:00:00' for function str_to_date")
  mysql.copy_table(table, filepath)
time=2021-03-11 09:37:10 logger_name=pipelinewise.fastsync.mysql_to_postgres log_level=INFO message=
        -------------------------------------------------------
        SYNC FINISHED - SUMMARY
        -------------------------------------------------------
            Total tables selected to sync  : 8
            Tables loaded successfully     : 8
            Exceptions during table sync   : []

            Pool size                      : 1
            Runtime                        : 0:00:59.075908
        -------------------------------------------------------
```

**Comment by lephuhai** [comment]
My **tap-mysql** configure like this, please help some ideas to find out the problem @Samira-El 

```yaml
---

id: "mysql_web_warehouse"                     # Unique identifier of the tap
name: "web_warehouse MySQL Database"          # Name of the tap
type: "tap-mysql"                      # !! THIS SHOULD NOT CHANGE !!
owner: "demo@eway.vn"              # Data owner to contact
db_conn:
  host: "mysql"                       # MySQL/ MariaDB host
  port: 3306                           # MySQL/ MariaDB port
  user: "root"                       # MySQL/ MariaDB user
  password: "password"               # Plain string or vault encrypted
  dbname: "pushsale"                  # MySQL/ MariaDB database name
target: "postgres_dwh"                    # ID of the target connector where the data will be loaded
batch_size_rows: 20000                 # Batch size for the stream to optimise load performance
stream_buffer_size: 0                  # In-memory buffer size (MB) between taps and targets for asynchronous data pipes
schemas:
  - source_schema: "pushsale"             # Source schema (aka. database) in MySQL/ MariaDB with tables
    target_schema: "public"        # Target schema in the destination Data Warehouse
    target_schema_select_permissions:  # Optional: Grant SELECT on schema and tables that created
      - developer
    tables:
      - table_name: "advertisers"
        replication_method: "LOG_BASED"
      - table_name: "offers"
        replication_method: "LOG_BASED"
      - table_name: "leads"
        replication_method: "LOG_BASED"
      - table_name: "leads_meta"
        replication_method: "LOG_BASED"
      - table_name: "users"
        replication_method: "LOG_BASED"
      - table_name: "opportunities"
        replication_method: "LOG_BASED"
      - table_name: "opportunity_attributes"
        replication_method: "LOG_BASED"
      - table_name: "orders"
        replication_method: "LOG_BASED"
```
