### ISSUE TITLE
Where does pipelinewise look for certificate files when Postgres tap demands client side SSL certs?

### ISSUE THREAD

**Issue by gerardjp** [transferwise/pipelinewise#743]
I'm trying to upgrade an existing connection (postgres tap to postgres target) to use forced client side SSL. Is there a specific default location where pipelinewise looks for these key and cert files?

I've set `ssl: "true"` and then, during importing new tap config, the log correctly says: `connection requires a valid client certificate`
```
time=2021-07-15 09:38:24 logger_name=pipelinewise.cli.commands log_level=ERROR message=time=2021-07-15 09:38:24 logger_name=tap_postgres log_level=CRITICAL message=FATAL:  connection requires a valid client certificate
```

The following works from the system where the target resides:
```
psql "sslmode=verify-ca sslrootcert=/root/.pipelinewise/certs/server-ca.pem sslcert=/root/.pipelinewise/certs/client-cert.pem sslkey=/root/.pipelinewise/certs/client-key.pem hostaddr=<snip> port=5432 user=<snip> dbname=<snip>"
```

I've looked at the source code and the tap does indeed not support configuring the file locations. https://github.com/transferwise/pipelinewise/blob/master/pipelinewise/fastsync/commons/tap_postgres.py#L129

As for the connection info, I would suggest something like this:

```
# Source (Tap) - PostgreSQL connection details
db_conn:
  # <regular connection attributes>
  ssl: "true"
  sslrootcert: /root/.pipelinewise/[target]/[tap]/certs/server-ca.pem
  sslcert: /root/.pipelinewise/[target]/[tap]/certs/client-cert.pem
  sslkey: /root/.pipelinewise/[target]/[tap]/certs/client-key.pem
```

I'm not a hardcore developer and not sure if I missed anything to enable client side SSL. Hence the question and not an immediate pull request.

Thanks for any comments!
