### ISSUE TITLE
mysql_snowflake target cannot disable hard_delete 

### ISSUE THREAD

**Issue by baderkha** [transferwise/pipelinewise#766]
**Describe the bug**
placing hard_delete under the db_con in the yml file does not get respected 

**To Reproduce**
configure mysql to snowflake pipeline and setup the snowflake yml file to have hard_delete:false , no matter what the pipeline will still delete _sdc_deleted at records.

**Expected behavior**
placing hard_delete as false in db_con in the yml file should be respected and leave records with _sdc_deleted at alone

*screenshot*
![Screen Shot 2021-08-05 at 5 24 52 PM](https://user-images.githubusercontent.com/63215659/128423335-e6f8dcf5-1e8c-4b77-af86-1caa9aae4cfd.png)

**Your environment**
 - PipelineWise  latest as of this date
 - mysql tap source
 - snowflake target

**Additional context**

**Comment by Samira-El** [comment]
Hey, try putting the `hard_delete` in the tap instead, in the target section, like so:
```
# ------------------------------------------------------------------------------
# Source (Tap) - MySQL connection details
# ------------------------------------------------------------------------------
db_conn:
  host: "db_mysql_source"                  # PostgreSQL host
  port: 3306                    # PostgreSQL port
  user: "pipelinewise"                  # PostgreSQL user
  password: "secret"          # Plain string or vault encrypted
  dbname: "mysql_source_db"                  # PostgreSQL database name


# ------------------------------------------------------------------------------
# Destination (Target) - Target properties
# Connection details should be in the relevant target YAML file
# ------------------------------------------------------------------------------
target: "snowflake_dev"                 # ID of the target connector where the data will be loaded
hard_delete: false
```
