### ISSUE TITLE
Could not run pipelinewise after switching from 0.31.1 to 0.35.2

### ISSUE THREAD

**Issue by sphinks** [transferwise/pipelinewise#792]
I have updated pipelinewise from 0.31.1 to 0.35.2 version. And my previously working pipeline Postgres->Snowflake starts to fail with strange error:

```
time=2021-09-04 12:32:45 logger_name=pipelinewise.cli.utils file=/app/pipelinewise/pipelinewise/cli/utils.py:95 log_level=DEBUG message=No file at /root/.pipelinewise/snowflake/postgres/state.json
Traceback (most recent call last):
  File "/app/pipelinewise/pipelinewise/cli/pipelinewise.py", line 155, in create_filtered_tap_properties
    for stream_idx, stream in enumerate(properties.get('streams', tap_properties)):
AttributeError: 'NoneType' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//.virtualenvs/pipelinewise/bin/pipelinewise", line 33, in <module>
    sys.exit(load_entry_point('pipelinewise', 'console_scripts', 'pipelinewise')())
  File "/app/pipelinewise/pipelinewise/cli/__init__.py", line 230, in main
    getattr(ppw_instance, args.command)()
  File "/app/pipelinewise/pipelinewise/cli/pipelinewise.py", line 975, in run_tap
    ) = self.create_filtered_tap_properties(
  File "/app/pipelinewise/pipelinewise/cli/pipelinewise.py", line 271, in create_filtered_tap_properties
    raise Exception(f'Cannot create JSON file - {exc}') from exc
Exception: Cannot create JSON file - 'NoneType' object has no attribute 'get'
```

I could see another error in log, that could by root cause of the error:
```
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.
time=2021-09-04 12:39:12 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=Discovering postgres (tap-postgres) tap in snowflake (target-snowflake) target...
time=2021-09-04 12:39:24 logger_name=pipelinewise.cli.commands log_level=ERROR message=/bin/bash: line 1: /.virtualenvs/transform-field/bin/transform-field: No such file or directory

[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:   11.8s
[Parallel(n_jobs=-1)]: Done   1 out of   1 | elapsed:   11.8s finished
time=2021-09-04 12:39:24 logger_name=pipelinewise.cli.pipelinewise log_level=INFO message=
            -------------------------------------------------------
            IMPORTING YAML CONFIGS FINISHED
            -------------------------------------------------------
                Total targets to import        : 1
                Total taps to import           : 1
                Taps imported successfully     : 0
                Taps failed to import          : ["Post import tap checks failed in tap postgres: ['/bin/bash: line 1: /.virtualenvs/transform-field/bin/transform-field: No such file or directory\\n']"]
                Runtime                        : 0:00:11.755725
            -------------------------------------------------------
```
My tap configuration is like this:
```
---

# ------------------------------------------------------------------------------
# General Properties
# ------------------------------------------------------------------------------
id: "postgres"                  # Unique identifier of the tap
name: "Postgres Database"       # Name of the tap
type: "tap-postgres"                   # !! THIS SHOULD NOT CHANGE !!
owner: "somebody@foo.com"              # Data owner to contact
#send_alert: False                     # Optional: Disable all configured alerts on this tap


# ------------------------------------------------------------------------------
# Source (Tap) - PostgreSQL connection details
# ------------------------------------------------------------------------------
db_conn:
  host: "host"             # PostgreSQL host
  port: 5432                           # PostgreSQL port
  user: "user"         # PostfreSQL user
  password: "pass"     # Plain string or vault encrypted
  dbname: "db_name"             # PostgreSQL database name
  filter_schemas: "public"   # Optional: Scan only the required schemas
                                       #           to improve the performance of
                                       #           data extraction
  fastsync_parallelism: 4

# ------------------------------------------------------------------------------
# Destination (Target) - Target properties
# Connection details should be in the relevant target YAML file
# ------------------------------------------------------------------------------
target: "snowflake"                    # ID of the target connector where the data will be loaded
batch_size_rows: 20000                 # Batch size for the stream to optimise load performance
stream_buffer_size: 0                  # In-memory buffer size (MB) between taps and targets for asynchronous data pipes


# ------------------------------------------------------------------------------
# Source to target Schema mapping
# ------------------------------------------------------------------------------
schemas:

  - source_schema: "public"            # Source schema in postgres with tables
    target_schema: "raw"    # Target schema in the destination Data Warehouse
    #target_schema_select_permissions:  # Optional: Grant SELECT on schema and tables that created
    #  - grp_stats

    # List of tables to replicate from Postgres to destination Data Warehouse
    #
    # Please check the Replication Strategies section in the documentation to understand the differences.
    # For LOG_BASED replication method you might need to adjust the source mysql/ mariadb configuration.
    tables:

      - table_name: "facebook_log"
        replication_method: "FULL_TABLE"
```

Could not find any changes in documentation in configuration of Pipelinewise in version > 31.1. Any hints?
