### ISSUE TITLE
Pipelinewise bails when syncing empty tables, msg: No such file or directory: `..._fastsync_YDLKIZ9O.csv.gz`

### ISSUE THREAD

**Issue by gerardjp** [transferwise/pipelinewise#806]
**Describe the bug**
When replicating tables between a tap (Postgres) and a target (also Postgres) with no records in them, pipelinewise/fastsync returns with the following error message for every empty table:

`No such file or directory: ... /root/.pipelinewise/tmp/pipelinewise___SNIP___20210927-144614-856033_fastsync_YDLKIZ9O.csv.gz`

**To Reproduce**

1. Have a running sync in place as described above (tap:PG > target:PG)
1. Add an empty table on the tap side
2. Run the replication again
4. It then fails to complete the replication altogether with a `No such file or directory` message per empty table.

**Expected behavior**
Complete the sync without erroring out.

**Your environment**
- Running this with the dockerized pipelinewise build. Tried it with latest and tag: v0.35.2
 - Source type Postgres v11
 - Target type Postgres v11

Source config:
```
---
id: "tap_accept"
name: "Accept tap test"
type: "tap-postgres"

db_conn:
  host: "20.20.20.21"
  port: 5432
  user: "postgres"
  password: "XXX"
  dbname: "tap_accept"
  logical_poll_total_seconds: 120

target: "target_accept"
batch_size_rows: 20000

schemas:
  - source_schema: "public"
    target_schema: "public"

    tables:
      - table_name: "androidappversion"
        replication_method: "FULL_TABLE"
    # ... SNIP ...
```

Target config:
```
---
id: "target_accept"
name: "Main Postgres base"
type: "target-postgres"

db_conn:
  host: "20.20.20.21"
  port: 5432
  user: "postgres"
  password: "XXX"
  dbname: "target_accept"
```
**Additional context**
- Above configs are censored (to avoid information disclosure) but accurate.
- I've seen this in a live setup and completely rebuild a local setup where I can reproduce problem.
- It breaks with FULL_TABLE as well as with LOG_BASED.
- When I remove all tables from the tap config that generate the error the sync works fine.
