### ISSUE TITLE
field_paths silently ignored during run_tap with fastsync

### ISSUE THREAD

**Issue by gwax** [transferwise/pipelinewise#943]
**Describe the bug**
At present, field_paths for transformations are not compatible with FastSync. When validating a configuration with `pipelinewise validate`, an error is emitted, as expected:

```
pipelinewise.cli.errors.InvalidTransformationException: This tap-target combo has FastSync component and is configuring a transformation on json properties which are not supported by FastSync!
```

However, when a tap is run with `pipelinewise run_tap ...` without invoking validation, the field_paths value is completely ignored and the transform is applied to the entire column

**To Reproduce**
1. Prepare a tap/target combination that defaults to fast sync (e.g. postgres-postgres)
2. Add a json column to a data table
3. configure a field transformation on the field with field_paths specified

   ```yml
   - table_name: table
     replication_method: FULL_TABLE
     transformations:
       - column: json_column
         field_paths:
           - some/path/to/node
         type: SET-NULL
   ```

4. Run the tap without validation
5. See `json_column` fully `NULL` in target

**Expected behavior**
Either:

1. failure with error on `pipelinewise import`
2. failure with error on `pipelinewise run_tap`
3. fast sync disabled for tap/target combination

**Your environment**
 - Version of PipelineWise: 0.43.1
 - Source type: postgres
 - Target type: postgres

**Additional context**
